# Базовые настройки приложения
spring:
  application:
    name: spring-boot-app
  web:
    resources:
      static-locations:
        - classpath:/public/
        - classpath:/static/
      cache:
        period: 0
  # Отключаем PostgreSQL, используем H2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  # Настройки JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  # Полностью отключаем Liquibase
  liquibase:
    enabled: false
  # Отключаем H2 консоль
  h2:
    console:
      enabled: true
      path: /h2-console

# Настройки сервера
server:
  port: 8080

# Настройки логирования
logging:
  level:
    root: INFO
    com:
      example:
        springbootapp: DEBUG

# Настройки Ollama API
ollama:
  api:
    url: http://localhost:11434
  model: llama2:latest
