# Базовые настройки приложения
spring:
  application:
    name: spring-boot-app
  web:
    resources:
      static-locations:
        - classpath:/public/
        - classpath:/static/
      cache:
        period: 0
  # Настройки подключения к PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1356
  # Настройки JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Включаем Liquibase для миграций
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

# Настройки сервера
server:
  port: 8080

# Настройки логирования
logging:
  level:
    root: INFO
    com:
      example:
        springbootapp: DEBUG

# Настройки Ollama API
ollama:
  api:
    url: http://localhost:11434
  model: llama2:latest
